account_id = "8995c0f49cdcf57eb54d2c1e52b7d2f3"
name = "cache-dependency-binary"
type = "javascript"
route = "https://workers.cloudflare.com/get-binary*"
workers_dev = false
zone_id = "29ed9c83c2c78d6967876c4053ec8154"